In [48]:
import pandas as pd

df = pd.read_csv("netflix_reviews.csv")

# read : 파일을 읽는 함수

In [49]:
df.head()

# df.head = DataFrame 내의 처음 n 줄의 데이터 출력

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion
0,4f8e23e8-860d-4cf2-8a07-0735e9e94dac,Eddy Wijaya,Can't open,1,0,NaN,2024-10-19 14:23:00,NaN
1,b36f1a48-1ac6-4dc0-a895-50a520205fef,Tirthesh Poojari,The best app😍😍😍😍😍😍😍😍😍😍😍😍😍,5,0,NaN,2024-10-19 14:17:36,NaN
2,61ec00cf-0ced-4d96-98b5-b67cde1d4c83,Trupti Ambade,Most of the famous Korean drama are not dubbed...,2,0,8.136.0 build 3 50908,2024-10-19 14:17:18,8.136.0 build 3 50908
3,1a05f4ef-ff9e-46cb-948b-4bd3a27d5d53,Sanju Sahu,It's superb but can you please add comments se...,5,0,8.136.0 build 3 50908,2024-10-19 14:16:43,8.136.0 build 3 50908
4,cb98f179-4996-445e-a896-f49313a8c84b,Billy Barras,The only reason I didn't give it four stars is...,1,0,8.136.0 build 3 50908,2024-10-19 14:16:20,8.136.0 build 3 50908

In [52]:
# 전처리 함수
def preprocess_text(text):
    if isinstance(text, float):
        return ""
    text = text.lower()  # 대문자를 소문자로
    text = re.sub(r'[^\w\s]', '', text)  # 구두점 제거
    text = re.sub(r'\d+', '', text)  # 숫자 제거
    text = text.strip()  # 띄어쓰기 제외하고 빈 칸 제거
    return text

# def preprocess_text : 텍스트를 정제하고 필요한 형태로 전처리

In [54]:
# 결측값이 포함된 행 제거
df_dropped_rows = df.dropna()

# 결측값이 포함된 열 제거
df_dropped_cols = df.dropna(axis=1)

In [56]:
df_dropped_rows

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion
2,61ec00cf-0ced-4d96-98b5-b67cde1d4c83,Trupti Ambade,Most of the famous Korean drama are not dubbed...,2,0,8.136.0 build 3 50908,2024-10-19 14:17:18,8.136.0 build 3 50908
3,1a05f4ef-ff9e-46cb-948b-4bd3a27d5d53,Sanju Sahu,It's superb but can you please add comments se...,5,0,8.136.0 build 3 50908,2024-10-19 14:16:43,8.136.0 build 3 50908
4,cb98f179-4996-445e-a896-f49313a8c84b,Billy Barras,The only reason I didn't give it four stars is...,1,0,8.136.0 build 3 50908,2024-10-19 14:16:20,8.136.0 build 3 50908
5,14196040-6174-45bf-8097-b963dfe29ebc,David De Zalze,Amazing.,5,0,8.136.0 build 3 50908,2024-10-19 14:10:28,8.136.0 build 3 50908
6,c359553c-802c-4443-81ec-efa6cae73357,nocure mwita,Pure greatness,5,0,8.81.0 build 8 50478,2024-10-19 14:10:16,8.81.0 build 8 50478
...,...,...,...,...,...,...,...,...
116923,9996579a-cf67-40a6-94eb-9ccd63c7d46a,dady mon mari,How can I delete one of the users? Please. Hel...,3,0,8.104.0 build 5 50619,2024-03-01 04:54:36,8.104.0 build 5 50619
116924,f2e61d1c-21eb-44d2-924c-35df26ed3bd2,Romnick Arcangel,Good app in easy to use,5,0,8.96.1 build 16 50568,2023-12-22 22:08:03,8.96.1 build 16 50568
116925,cbb04dd9-1a1d-46df-80a4-8ae987fe5d85,Ciaran Worthington,Everytime I watch a show it goes so dark so I ...,1,0,7.48.0 build 10 34747,2020-08-22 14:58:10,7.48.0 build 10 34747
116927,4957f9e7-d7f4-4a52-9764-031cebcac83f,Captain Jeoy,I love Netflix. I always enjoy my time using it.,5,0,8.34.0 build 4 50250,2022-08-15 16:16:30,8.34.0 build 4 50250
116929,32870f7f-c461-4256-b602-75244ca60248,A Google user,Rate is very expensive.. bcos we see netflix s...,1,0,7.17.0 build 13 34346,2019-07-21 09:41:42,7.17.0 build 13 34346